---
version: "2.1"
services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Motdepassetùrèssecret

  php-myadmin:
    container_name: php-myadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    links: 
    - mysql:db


