---
version: "2.1"
services:

  nginx:
    image: nginx
    volumes:
    - /opt/templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80